### ISSUE TITLE
Shut-off fans

### ISSUE THREAD

**Issue by Sale3054** [Sale3054/mistyRobotics#11]
Investigate the possibility of temporarily shutting off the fans in Misty's face to listen for noises.

If possible, Misty should be capable of shutting it off for an approximate 2-3 seconds to listen to any loud noises previously observed through the fans.

**Comment by ghost** [comment]
No known method to do this, put question was posed to Misty community and we will check back on answer soon.

**Comment by Sale3054** [comment]
We already have an answer to this question. I spoke with Justin on Tuesday.
