### ISSUE TITLE
Send confirmation email

### ISSUE THREAD

**Issue by Sale3054** [Sale3054/mistyRobotics#17]

**Comment by ghost** [comment]
Resources for sending email:
https://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript
This recommends sending email with Mandrill web API.
Probably going to be similar to texting.
In addition, we could possibly link up Google Forms to store and access user data. I am familiar with Google Script and Web API which can send emails, so Misty would just need a means to interface with that.

**Comment by ghost** [comment]
Due Thursday 2/21
